### PR TITLE
ansibleapp-base arbitrary uid support; example arbitrary uid project

### PR DESCRIPTION
**Pull request by jcpowermac**
This PR adds the ability to run ansibleapp(-base) containers under OpenShift
using the restricted scc and arbitrary uid support.  These changes were based on [existing work](https://github.com/RHsyseng/container-rhel-examples/tree/master/starter-arbitrary-uid)

The helloworld nginx example also runs in restricted scc with arbitrary uid support.
It was used to testing the ansibleapp-base modifications.

Testing:

- Building the images, running `helloworld-ansibleapp` via docker
[building and docker run test](https://asciinema.org/a/111877)
[script while testing above](https://gist.github.com/jcpowermac/aa73a5e4734836da0a026dc41d867e1b)

- Using the ansible-service-broker to test running `helloworld-ansibleapp`
[asb testing](https://asciinema.org/a/111884)

### CODE REVIEW

**Comment by jcpowermac** [comment]
I didn't notice that travis had failed and I am not quite sure why.  I just pushed an empty commit to trigger a build and no issues.  When someone has a chance if you could please review.  Thanks!

**Comment by fabianvf** [comment]
Hi @jcpowermac, thanks a ton for the contribution. We've been a little slammed with summit coming up, I just wanted to let you know that we'll be taking a look at this post summit. We will also update our docs and getting started resources to explain the changes that were made for summit. Sorry for the delay/silence!

**Comment by fabianvf** [comment]
all right @jcpowermac, sorry this has been hanging around so long, things went a little crazy leading up to summit. You may have noticed that we went through a name change, now instead of ansible apps we are ansible playbook bundles (apbs). ansibleapp-library is in the process of being replaced by [apb-examples](https://github.com/fusor/apb-examples). 

The basic structure of the Dockerfile remains the same, as does much of the app so I think this patch would be pretty easy to copy over. Biggest difference will be that we don't build the dependent images in the repository anymore, we just store the metadata, deployment playbooks/roles, and Dockerfile for the metacontainer. I'd be happy to assist with the update, our documentation is lagging a bit behind the summit changes right now. 

I was also curious if you had any documentation/resources on the anyuid stuff? I checked out the [Dockerfile best practices docs](http://docs.projectatomic.io/container-best-practices/#create) but it looks like the Users section was TBD. Not crazy familiar with this so was hoping to cure my ignorance.

If you want to meet in person/over the phone to talk about this that's fine too, just let me know!

**Comment by jcpowermac** [comment]
No longer need this PR.

**Pull request closed without merging**
